### ISSUE TITLE
Remove support for partial IPv4 addresses from netaddr constructors

### ISSUE THREAD

**Issue by drkjam** [netaddr/netaddr#110]
Looks like this are causing a problem for downstream library users

http://lists.openstack.org/pipermail/openstack-dev/2015-August/072610.html

This behaviour needs to change.

**Comment by sschaap** [comment]
This issue is likely **not** caused by the `implicit_prefix` argument for the `IPNetwork` constructor, which is `False` by default. Rather, this behavior is (incorrectly?) still present with `implicit_prefix=False`, at least for IPv4 networks. This seems due to to an invocation of `_ipv4.expand_partial_address()` which happens unconditionally if the address cannot be parsed.

https://github.com/drkjam/netaddr/blob/ebf714601e8cd6234575422f876d4d579b202b1a/netaddr/ip/__init__.py#L795

**Comment by cdwchriburg** [comment]
Any chance we can get this fixed?  Perhaps providing some form of "strict" flag for `IPNetwork` similar to `INET_PTON` 

Seems like this would be very useful as I would think most folks dealing with networks and this library wouldn't expect the string"10" to be parsed and accepted as a valid IPv4 address (regardless if technically that might be true).

**Comment by jstasiak** [comment]
Your summary is accurate @sschaap.

I'll deprecate this behavior in the next minor release (1.1.0) and remove in netaddr 2.x (the next round of backwards-incompatible changes).

**Comment by jstasiak** [comment]
I changed my mind a little bit. The `implicit_prefix` feature has been removed in 1.0.0 and I think the deprecation warning given pre-1.0.0 is sufficient to consider the remaining behavior (expanding partial IPv4 addresses to four octets) unwanted.

I'll remove/fix this in 1.1.0 (with appropriate documentation so that it's not a surprise).

**Comment by jstasiak** [comment]
Removed in 1.1.0.
