### ISSUE TITLE
TypeError: argument of type 'IPAddress' is not iterable

### ISSUE THREAD

**Issue by hoyeunglee** [netaddr/netaddr#179]
![image](https://user-images.githubusercontent.com/5094741/43525312-07eb9366-95d4-11e8-8cee-48b39a46773f.png)

**Comment by tylwright** [comment]
This isn't _exactly_ your issue but since I found your ticket based on my similar issue, I figured I'd post what fixed it here.

I was also receiving the same error when using netaddr in my Django app.  Turns out that GenericIPAddressField doesn't seem to work with IPNetwork.  In order to resolve the issue, I have to change my model back to using IPAddressField instead of GenericIPAddressField.

**Comment by tpickle-py** [comment]
You are asking if a network is in an IP address.

if you need to remove the broadcast from the Search subnet, I would use an IPSET, and then remove the broadcast from the SET

Example
```
from netaddr import *
ip = IPNetwork("y.y.y.y/y")
search_nets = IPSet(IPNetwork("**x.x.x.x/x**"))
search_nets.remove(IPNetwork("**x.x.x.x/x**").broadcast)

if ip in search_nets:
    print("Yes")
else:
    print("No")
```

**Comment by jstasiak** [comment]
With what @tpickle-py said I think this can be closed.
