### ISSUE TITLE
Valid_ipv4 returns True on invalid ip address

### ISSUE THREAD

**Issue by devdil** [netaddr/netaddr#186]
The method valid_ipv4 utility invalid ip addresses as True

for e.g. valid_ipv4("10") = True

**Comment by umanther** [comment]
This is actually not invalid input.

By default, valid_ipv4 uses the inet_aton() C function to verify input which follows the following input formatting rules:
       a.b.c.d   Each of the four numeric parts specifies a byte of the
                 address; the bytes are assigned in left-to-right order to
                 produce the binary address.

       a.b.c     Parts a and b specify the first two bytes of the binary
                 address.  Part c is interpreted as a 16-bit value that
                 defines the rightmost two bytes of the binary address.
                 This notation is suitable for specifying (outmoded) Class B
                 network addresses.

       a.b       Part a specifies the first byte of the binary address.
                 Part b is interpreted as a 24-bit value that defines the
                 rightmost three bytes of the binary address.  This notation
                 is suitable for specifying (outmoded) Class A network
                 addresses.

       a         The value a is interpreted as a 32-bit value that is stored
                 directly into the binary address without any byte
                 rearrangement.

Therefore, '10' falls under the 4th option (a) where the number is treated as a 32-bit value.  Written in doted decimal format it would be '0.0.0.10' or in hex \x00\x00\x00\x0A
Python3 shows it as a byte array b'\x00\x00\x00\n' (\n newline being the ascii character 10)

To validate the dotted decimal notation pass the INET_PTON flag to have the function use inet_pton() instead of inet_aton() which evaluates ipv4 and ipv6 addresses using proper formatting requirements:
netaddr.valid_ipv4('10', flags=netaddr.INET_PTON)

**Comment by jstasiak** [comment]
I believe @umanther's explanation is satisfactory and this can be closed.
